<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bats</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\b(if|case)\b|(\{|\b(do)\b)$</string>
	<key>foldingStopMarker</key>
	<string>^\s*(\}|(done|fi|esac)\b)</string>
	<key>keyEquivalent</key>
	<string>^~B</string>
	<key>name</key>
	<string>Bash Automated Testing System (bats)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#pipeline</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#list</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#compound-command</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#loop</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function-definition</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#interpolation</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#heredoc</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#herestring</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#redirection</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#pathname</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#support</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>case-clause</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=\S)</string>
					<key>end</key>
					<string>;;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.case-clause.bats</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.scope.case-clause.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(\(|(?=\S))</string>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.case-pattern.bats</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\)</string>
							<key>name</key>
							<string>meta.scope.case-pattern.bats</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\|</string>
									<key>name</key>
									<string>punctuation.separator.pipe-sign.bats</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#string</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#variable</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#interpolation</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#pathname</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;=\))</string>
							<key>end</key>
							<string>(?=;;)</string>
							<key>name</key>
							<string>meta.scope.case-clause-body.bats</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>$self</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.bats</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;!\S)(#)(?!\{).*$</string>
					<key>name</key>
					<string>comment.line.number-sign.bats</string>
				</dict>
			</array>
		</dict>
		<key>compound-command</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\[{1,2})</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.logical-expression.bats</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\]{1,2})</string>
					<key>name</key>
					<string>meta.scope.logical-expression.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#logical-expression</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\({2})</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.bats</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\){2})</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.bats</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.other.math.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#math</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.subshell.bats</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>name</key>
					<string>meta.scope.subshell.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;=\s|^)(\{)(?=\s|$)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.group.bats</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?&lt;=^|;)\s*(\})</string>
					<key>name</key>
					<string>meta.scope.group.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>function-definition</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(function)\s+([^\s\\]+)(?:\s*(\(\)))?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.bats</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.bats</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.bats</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;|&amp;|$</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.bats</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.function.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b([^\s\\=]+)\s*(\(\))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.bats</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.bats</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;|&amp;|$</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.bats</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.function.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>heredoc</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;&lt;)-("|'|)(RUBY)\2</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.heredoc.bats</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.bats</string>
						</dict>
					</dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.bats</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.ruby.embedded.bats</string>
					<key>end</key>
					<string>^\t*(RUBY)\b</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.bats</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.unquoted.heredoc.no-indent.ruby.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.ruby</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;&lt;)("|'|)(RUBY)\2</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.heredoc.bats</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.bats</string>
						</dict>
					</dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.bats</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.ruby.embedded.bats</string>
					<key>end</key>
					<string>^(RUBY)\b</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.bats</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.unquoted.heredoc.ruby.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.ruby</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;&lt;)-("|'|)(PYTHON)\2</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.heredoc.bats</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.bats</string>
						</dict>
					</dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.bats</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.python.embedded.bats</string>
					<key>end</key>
					<string>^\t*(PYTHON)\b</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.bats</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.unquoted.heredoc.no-indent.python.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.python</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;&lt;)("|'|)(PYTHON)\2</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.heredoc.bats</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.bats</string>
						</dict>
					</dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.bats</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.python.embedded.bats</string>
					<key>end</key>
					<string>^(PYTHON)\b</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.bats</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.unquoted.heredoc.python.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.python</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;&lt;)-("|'|)(APPLESCRIPT)\2</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.heredoc.bats</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.bats</string>
						</dict>
					</dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.bats</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.applescript.embedded.bats</string>
					<key>end</key>
					<string>^\t*(APPLESCRIPT)\b</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.bats</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.unquoted.heredoc.no-indent.applescript.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.applescript</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;&lt;)("|'|)(APPLESCRIPT)\2</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.heredoc.bats</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.bats</string>
						</dict>
					</dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.bats</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.applescript.embedded.bats</string>
					<key>end</key>
					<string>^(APPLESCRIPT)\b</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.bats</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.unquoted.heredoc.applescript.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.applescript</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;&lt;)-("|'|)(HTML)\2</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.heredoc.bats</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.bats</string>
						</dict>
					</dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.bats</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html.embedded.bats</string>
					<key>end</key>
					<string>^\t*(HTML)\b</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.bats</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.unquoted.heredoc.no-indent.html.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.basic</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;&lt;)("|'|)(HTML)\2</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.heredoc.bats</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.bats</string>
						</dict>
					</dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.bats</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html.embedded.bats</string>
					<key>end</key>
					<string>^(HTML)\b</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.bats</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.unquoted.heredoc.html.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.basic</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;&lt;)-("|'|)(MARKDOWN)\2</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.heredoc.bats</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.bats</string>
						</dict>
					</dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.bats</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html.markdown.embedded.bats</string>
					<key>end</key>
					<string>^\t*(MARKDOWN)\b</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.bats</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.unquoted.heredoc.no-indent.markdown.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.markdown</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;&lt;)("|'|)(MARKDOWN)\2</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.heredoc.bats</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.bats</string>
						</dict>
					</dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.bats</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html.markdown.embedded.bats</string>
					<key>end</key>
					<string>^(MARKDOWN)\b</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.bats</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.unquoted.heredoc.markdown.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.markdown</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;&lt;)-("|'|)(TEXTILE)\2</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.heredoc.bats</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.bats</string>
						</dict>
					</dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.bats</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html.textile.embedded.bats</string>
					<key>end</key>
					<string>^\t*(TEXTILE)\b</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.bats</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.unquoted.heredoc.no-indent.textile.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.textile</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;&lt;)("|'|)(TEXTILE)\2</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.heredoc.bats</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.bats</string>
						</dict>
					</dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.bats</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html.textile.embedded.bats</string>
					<key>end</key>
					<string>^(TEXTILE)\b</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.bats</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.unquoted.heredoc.textile.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.textile</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;&lt;)-("|'|)\\?(\w+)\2</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.heredoc.bats</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.bats</string>
						</dict>
					</dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.bats</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^\t*(\3)\b</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.bats</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.unquoted.heredoc.no-indent.bats</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;&lt;)("|'|)\\?(\w+)\2</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.heredoc.bats</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.bats</string>
						</dict>
					</dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.bats</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(\3)\b</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.bats</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.unquoted.heredoc.bats</string>
				</dict>
			</array>
		</dict>
		<key>herestring</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.herestring.bats</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.single.herestring.bats</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.bats</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.bats</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&lt;&lt;&lt;)((')[^']*('))</string>
					<key>name</key>
					<string>meta.herestring.bats</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.herestring.bats</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.herestring.bats</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.bats</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.bats</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&lt;&lt;&lt;)((")(\\("|\\)|[^"])*("))</string>
					<key>name</key>
					<string>meta.herestring.bats</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.herestring.bats</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.herestring.bats</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&lt;&lt;&lt;)(([^\s\\]|\\.)+)</string>
					<key>name</key>
					<string>meta.herestring.bats</string>
				</dict>
			</array>
		</dict>
		<key>interpolation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\$\({2}</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.bats</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\){2}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.bats</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.other.math.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#math</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>`</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.bats</string>
						</dict>
					</dict>
					<key>end</key>
					<string>`</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.bats</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.interpolated.backtick.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\[`\\$]</string>
							<key>name</key>
							<string>constant.character.escape.bats</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\$\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.bats</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.bats</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.interpolated.dollar.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?:if|then|else|elif|fi|for|in|do|done|select|case|continue|break|esac|while|until|return)\b</string>
					<key>name</key>
					<string>keyword.control.bats</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![-/])\b(?:export|declare|typeset|local|readonly)\b</string>
					<key>name</key>
					<string>storage.modifier.bats</string>
				</dict>
			</array>
		</dict>
		<key>list</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>;|&amp;&amp;|&amp;|\|\|</string>
					<key>name</key>
					<string>keyword.operator.list.bats</string>
				</dict>
			</array>
		</dict>
		<key>logical-expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>do we want a special rule for ( expr )?</string>
					<key>match</key>
					<string>=[=~]?|!=?|&lt;|&gt;|&amp;&amp;|\|\|</string>
					<key>name</key>
					<string>keyword.operator.logical.bats</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\S)-(nt|ot|ef|eq|ne|l[te]|g[te]|[a-hknoprstuwxzOGLSN])</string>
					<key>name</key>
					<string>keyword.operator.logical.bats</string>
				</dict>
			</array>
		</dict>
		<key>loop</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(for)\s+(?=\({2})</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.bats</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\b(done)\b</string>
					<key>name</key>
					<string>meta.scope.for-loop.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(for)\s+((?:[^\s\\]|\\.)+)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.bats</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.loop.bats</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\b(done)\b</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.bats</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.scope.for-in-loop.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(while|until)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.bats</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\b(done)\b</string>
					<key>name</key>
					<string>meta.scope.while-loop.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(select)\s+((?:[^\s\\]|\\.)+)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.bats</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.loop.bats</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\b(done)\b</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.bats</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.scope.select-block.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(case)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.bats</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\b(esac)\b</string>
					<key>name</key>
					<string>meta.scope.case-block.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\b(in)\b</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.control.bats</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=\b(?:esac)\b)</string>
							<key>name</key>
							<string>meta.scope.case-body.bats</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#comment</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#case-clause</string>
								</dict>
								<dict>
									<key>include</key>
									<string>$self</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(if)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.bats</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\b(fi)\b</string>
					<key>name</key>
					<string>meta.scope.if-block.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>math</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\+{1,2}|-{1,2}|!|~|\*{1,2}|/|%|&lt;[&lt;=]?|&gt;[&gt;=]?|==|!=|^|\|{1,2}|&amp;{1,2}|\?|\:|,|=|[*/%+\-&amp;^|]=|&lt;&lt;=|&gt;&gt;=</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.bats</string>
				</dict>
				<dict>
					<key>match</key>
					<string>0[xX]\h+</string>
					<key>name</key>
					<string>constant.numeric.hex.bats</string>
				</dict>
				<dict>
					<key>match</key>
					<string>0\d+</string>
					<key>name</key>
					<string>constant.numeric.octal.bats</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\d{1,2}#[0-9a-zA-Z@_]+</string>
					<key>name</key>
					<string>constant.numeric.other.bats</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\d+</string>
					<key>name</key>
					<string>constant.numeric.integer.bats</string>
				</dict>
			</array>
		</dict>
		<key>pathname</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=[a-zA-Z0-9_])=(?=\s*$|[^\s])</string>
					<key>name</key>
					<string>keyword.operator.assign.bats</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\s|:|=|^)~</string>
					<key>name</key>
					<string>keyword.operator.tilde.bats</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\*|\?</string>
					<key>name</key>
					<string>keyword.operator.glob.bats</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>([?*+@!])(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.extglob.bats</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.extglob.bats</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.extglob.bats</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.structure.extglob.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>pipeline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(time)\b</string>
					<key>name</key>
					<string>keyword.other.bats</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[|!]</string>
					<key>name</key>
					<string>keyword.operator.pipe.bats</string>
				</dict>
			</array>
		</dict>
		<key>redirection</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>[&gt;&lt;]\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.bats</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.bats</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.interpolated.process-substitution.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>comment</key>
					<string>valid: &amp;&gt;word &gt;&amp;word &gt;word [n]&gt;&amp;[n] [n]&lt;word [n]&gt;word [n]&gt;&gt;word [n]&lt;&amp;word (last one is duplicate)</string>
					<key>match</key>
					<string>&amp;&gt;|\d*&gt;&amp;\d*|\d*(&gt;&gt;|&gt;|&lt;)|\d*&lt;&amp;|\d*&lt;&gt;</string>
					<key>name</key>
					<string>keyword.operator.redirect.bats</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.bats</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.bats</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.bats</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.bats</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\$?"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.bats</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.bats</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\[\$`"\\\n]</string>
							<key>name</key>
							<string>constant.character.escape.bats</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variable</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#interpolation</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\$'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.bats</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.bats</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.dollar.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\(a|b|e|f|n|r|t|v|\\|')</string>
							<key>name</key>
							<string>constant.character.escape.ansi-c.bats</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\[0-9]{3}</string>
							<key>name</key>
							<string>constant.character.escape.octal.bats</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\x[0-9a-fA-F]{2}</string>
							<key>name</key>
							<string>constant.character.escape.hex.bats</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\c.</string>
							<key>name</key>
							<string>constant.character.escape.control-char.bats</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>support</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=^|\s)(?::|\.)(?=\s|;|&amp;|$)</string>
					<key>name</key>
					<string>support.function.builtin.bats</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![-/])\b(?:alias|bg|bind|builtin|caller|cd|command|compgen|complete|dirs|disown|echo|enable|eval|exec|exit|false|fc|fg|getopts|hash|help|history|jobs|kill|let|logout|popd|printf|pushd|pwd|read|readonly|set|shift|shopt|source|suspend|test|times|trap|true|type|ulimit|umask|unalias|unset|wait)\b</string>
					<key>name</key>
					<string>support.function.builtin.bats</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.bats</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\$)[-*@#?$!0_]</string>
					<key>name</key>
					<string>variable.other.special.bats</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.bats</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\$)[1-9]</string>
					<key>name</key>
					<string>variable.other.positional.bats</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.bats</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\$)[a-zA-Z_][a-zA-Z0-9_]*</string>
					<key>name</key>
					<string>variable.other.normal.bats</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\$\{</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.bats</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>variable.other.bracket.bats</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>!|:[-=?]?|\*|@|#{1,2}|%{1,2}|/</string>
							<key>name</key>
							<string>keyword.operator.expansion.bats</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.array.bats</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.array.bats</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(\[)([^\]]+)(\])</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.shell.bats</string>
	<key>uuid</key>
	<string>D001D6FC-04A3-4BB6-9588-A6BCE46DDEDB</string>
</dict>
</plist>
